  [[main]]
  name = "Accueil"
  identifier = "accueil"
  weight = 100
  url = "/"

  [[main]]
  name = "Articles"
  weight = 200
  identifier = "articles"
  url = "/article/"

  [[main]]
  name = "Portfolio"
  weight = 300
  identifier = "portfolio"
  url = "/portfolio/"

  [[main]]
  name = "A propos de moi"
  weight = 400
  identifier = "a-propos"
  url = "/a-propos/"

  [[main]]
  name = "Accomplissements"
  weight = 500
  identifier = "accomplissements"

  [[main]]
  name = "Certifications"
  weight = 520
  identifier = "certifications"
  url = "/certifications/"
  parent = "accomplissements"

  [[main]]
  name = "Contact"
  weight = 600
  identifier = "contact"
  url = "/contact/"

  [[footer]]
  name = "imprint"
  weight = 1
  identifier = "imprint"
  url = "/imprint/"